name = "4x8matrix/ollama"
version = "0.1.2"
description = "Luau ollama API"
authors = ["AsyncMatrix (hi@asyncmatrix.dev)"]
license = "MIT"

includes = ["src", "docs", "src/**/*", "docs/**/*", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
